from __future__ import annotations

LICENSE_STATUS_ACTIVE = "active"
LICENSE_STATUS_TRIAL = "trial"
LICENSE_STATUS_GRACE = "grace"
LICENSE_STATUS_EXPIRED = "expired"
LICENSE_STATUS_UNLICENSED = "unlicensed"

WRITE_ALLOWED_STATUSES = {
    LICENSE_STATUS_ACTIVE,
    LICENSE_STATUS_TRIAL,
    LICENSE_STATUS_GRACE,
}

